language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
script:
  - npm run build
env:
  - NODE_ENV=production
deploy:
  provider: pages
  skip-cleanup: true
  github-token: df6a6d59d0141ad698d722fac2b414efc62fef86  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
